name: map_location_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  sqflite: ^2.4.1
  path: ^1.9.0
  intl: ^0.19.0
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  
  share_plus: ^7.2.2
  fl_chart: ^0.66.0
  gpx: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_logo.png"
  min_sdk_android: 21 
flutter:
  uses-material-design: true
  assets:
    - assets/logos/
